export const TYPE_KO: Record<string, string> = {
  normal: "노말",
  fire: "불꽃",
  water: "물",
  grass: "풀",
  electric: "전기",
  ice: "얼음",
  fighting: "격투",
  poison: "독",
  ground: "땅",
  flying: "비행",
  psychic: "에스퍼",
  bug: "벌레",
  rock: "바위",
  ghost: "고스트",
  dragon: "드래곤",
  dark: "악",
  steel: "강철",
  fairy: "페어리",
};

export const TYPE_COLORS: Record<string, string> = {
  normal: "bg-gray-300 text-gray-700",
  fire: "bg-orange-400 text-white",
  water: "bg-blue-400 text-white",
  grass: "bg-green-400 text-white",
  electric: "bg-yellow-300 text-yellow-800",
  ice: "bg-cyan-300 text-cyan-800",
  fighting: "bg-red-500 text-white",
  poison: "bg-purple-400 text-white",
  ground: "bg-amber-500 text-white",
  flying: "bg-indigo-300 text-indigo-800",
  psychic: "bg-pink-400 text-white",
  bug: "bg-lime-400 text-lime-800",
  rock: "bg-stone-400 text-white",
  ghost: "bg-violet-500 text-white",
  dragon: "bg-blue-600 text-white",
  dark: "bg-neutral-700 text-white",
  steel: "bg-slate-400 text-white",
  fairy: "bg-rose-300 text-rose-800",
};
